echo "I am calling"
echo "I am from /Users/murali/Desktop/Groovy/DO180-apps/public/scripts/generate-bosh-vms-vitals.sh"
printf %100s |tr " " "="
echo "\n $PAYLOAD_FILE_PATH \n"
printf %100s |tr " " "="